- name: install celluloid
  become: yes
  ansible.builtin.package:
    name:
      - celluloid
    state: present

- name: create celluloid config directory
  ansible.builtin.file:
    path: ~/.config/celluloid
    state: directory

- name: link celluloid mpv.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/mpv.conf"
    dest: ~/.config/celluloid/mpv.conf
    state: link
