- name: install yay dependency
  become: yes
  ansible.builtin.package:
    name: base-devel
    state: present

- name: create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes

- name: allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.copy:
    content: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    dest: /etc/sudoers.d/11-install-aur_builder
    validate: "visudo -cf %s"

- name: install aur packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - yay
      # - microsoft-edge-stable-bin  # Edge from Flatpak has some issues (e.g. system proxy does not work).
      - google-chrome # Chromium doesn't support Google sync, so I use Google Chrome.
      - visual-studio-code-bin
      - nekoray-bin
    state: present
