- import_tasks: pacman.yml
  tags: [packages/pacman]

- import_tasks: pacman-reflector.yml
  tags: [packages/pacman-reflector]

- import_tasks: pacman-autopac.yml
  tags: [packages/pacman-autopac]

- import_tasks: aur.yml
  tags: [packages/aur]

- import_tasks: flatpak.yml
  tags: [packages/flatpak]

- import_tasks: onedrive.yml
  tags: [packages/onedrive]
